//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchSessionDetail
    {
        public int BSId { get; set; }
        public int RefCTId { get; set; }
        public int RefSessionId { get; set; }
        public System.DateTime SessionDate { get; set; }
        public System.DateTime SessionCompletedDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Status { get; set; }
        public string OtherDetails { get; set; }
    
        public virtual CandidateTechnicalExpertDetail CandidateTechnicalExpertDetail { get; set; }
        public virtual SessionListDetail SessionListDetail { get; set; }
    }
}
