//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateBatchDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateBatchDetail()
        {
            this.CandidateTechnicalExpertDetails = new HashSet<CandidateTechnicalExpertDetail>();
        }
    
        public int BatchId { get; set; }
        public string BatchName { get; set; }
        public int RefTechId { get; set; }
        public System.DateTime BatchStartDate { get; set; }
        public System.DateTime BatchEndDate { get; set; }
        public System.TimeSpan BatchStartTime { get; set; }
        public System.TimeSpan BatchEndTime { get; set; }
        public int TotalSession { get; set; }
        public int CompletedSession { get; set; }
        public string BatchStatus { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateTechnicalExpertDetail> CandidateTechnicalExpertDetails { get; set; }
        public virtual TechnologyMaster TechnologyMaster { get; set; }
    }
}
