//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dashrdku_database : DbContext
    {
        public dashrdku_database()
            : base("name=dashrdku_database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatchSessionDetail> BatchSessionDetails { get; set; }
        public virtual DbSet<CandidateBatchDetail> CandidateBatchDetails { get; set; }
        public virtual DbSet<CandidateTechnicalExpertDetail> CandidateTechnicalExpertDetails { get; set; }
        public virtual DbSet<MarketingRevenueDetail> MarketingRevenueDetails { get; set; }
        public virtual DbSet<OnBoardingMaster> OnBoardingMasters { get; set; }
        public virtual DbSet<OnBoardingPayment> OnBoardingPayments { get; set; }
        public virtual DbSet<PODetail> PODetails { get; set; }
        public virtual DbSet<ReportSubmissionDetail> ReportSubmissionDetails { get; set; }
        public virtual DbSet<RequestMaster> RequestMasters { get; set; }
        public virtual DbSet<SessionListDetail> SessionListDetails { get; set; }
        public virtual DbSet<SubmissionMaster> SubmissionMasters { get; set; }
        public virtual DbSet<TaskCategoryMaster> TaskCategoryMasters { get; set; }
        public virtual DbSet<TaskManageMaster> TaskManageMasters { get; set; }
        public virtual DbSet<TaskStatusDetail> TaskStatusDetails { get; set; }
        public virtual DbSet<CandidateAssign> CandidateAssigns { get; set; }
        public virtual DbSet<CandidateMarketingDetail> CandidateMarketingDetails { get; set; }
        public virtual DbSet<CandidateMaster> CandidateMasters { get; set; }
        public virtual DbSet<CandidateTimeLine> CandidateTimeLines { get; set; }
        public virtual DbSet<CommentDetail> CommentDetails { get; set; }
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public virtual DbSet<FollowUpMaster> FollowUpMasters { get; set; }
        public virtual DbSet<InterviewDetail> InterviewDetails { get; set; }
        public virtual DbSet<InterviewMode> InterviewModes { get; set; }
        public virtual DbSet<JobPortalMaster> JobPortalMasters { get; set; }
        public virtual DbSet<LeadMaster> LeadMasters { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<RecurringMaster> RecurringMasters { get; set; }
        public virtual DbSet<RecurringType> RecurringTypes { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<SalesServiceMaster> SalesServiceMasters { get; set; }
        public virtual DbSet<SubmissionDetail> SubmissionDetails { get; set; }
        public virtual DbSet<TargetDetail> TargetDetails { get; set; }
        public virtual DbSet<TaskMaster> TaskMasters { get; set; }
        public virtual DbSet<TaskTitleMaster> TaskTitleMasters { get; set; }
        public virtual DbSet<TeamDetail> TeamDetails { get; set; }
        public virtual DbSet<TechnologyMaster> TechnologyMasters { get; set; }
        public virtual DbSet<UserAccountDetail> UserAccountDetails { get; set; }
        public virtual DbSet<VisaTitleMaster> VisaTitleMasters { get; set; }
    }
}
