//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpMaster
    {
        public int FollowUpId { get; set; }
        public string FollowUpStatus { get; set; }
        public System.DateTime FollowUpDate { get; set; }
        public System.TimeSpan FollowUpTime { get; set; }
        public string FollowUpMessage { get; set; }
        public string FollowUpBy { get; set; }
        public int RefCandidateId { get; set; }
    
        public virtual CandidateMaster CandidateMaster { get; set; }
    }
}
