//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingRevenueDetail
    {
        public int MRId { get; set; }
        public System.DateTime RevenueDate { get; set; }
        public string PaidIn { get; set; }
        public int RefUserId { get; set; }
        public bool IsRevenueVerified { get; set; }
        public int RefCandidateId { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
    
        public virtual CandidateMaster CandidateMaster { get; set; }
        public virtual UserAccountDetail UserAccountDetail { get; set; }
    }
}
