//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnBoardingPayment
    {
        public int OBPId { get; set; }
        public decimal OBPAmount { get; set; }
        public string OBPStatus { get; set; }
        public string Remarks { get; set; }
        public System.DateTime OBPDate { get; set; }
        public Nullable<System.DateTime> OBPClearDate { get; set; }
        public string OBPReceivedIn { get; set; }
        public string UpdatedBy { get; set; }
        public int RefOBId { get; set; }
    
        public virtual OnBoardingMaster OnBoardingMaster { get; set; }
    }
}
