//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PODetail()
        {
            this.OnBoardingMasters = new HashSet<OnBoardingMaster>();
        }
    
        public int POId { get; set; }
        public string CandidateName { get; set; }
        public string RefOfCandidate { get; set; }
        public int RefSaleId { get; set; }
        public string JobType { get; set; }
        public string AppliedPosition { get; set; }
        public string InterviewSupport { get; set; }
        public string JobLocation { get; set; }
        public string EndClient { get; set; }
        public string VendorDetails { get; set; }
        public string RecruiterName { get; set; }
        public string TeamLeadName { get; set; }
        public decimal Rate { get; set; }
        public System.DateTime SignUpDate { get; set; }
        public string TrainerName { get; set; }
        public Nullable<System.DateTime> TrainingStartDate { get; set; }
        public Nullable<System.DateTime> TrainingEndDate { get; set; }
        public System.DateTime MarketingStartDate { get; set; }
        public System.DateTime MarketingEndDate { get; set; }
        public int AgreementPercentage { get; set; }
        public int AgreementMonths { get; set; }
        public string JobDescription { get; set; }
        public string OtherDetails { get; set; }
        public string AddBy { get; set; }
        public System.DateTime EnteryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime PODate { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnBoardingMaster> OnBoardingMasters { get; set; }
        public virtual UserAccountDetail UserAccountDetail { get; set; }
    }
}
