//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMaster
    {
        public int RequestId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.TimeSpan RequestTime { get; set; }
        public string Message { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public int ReqFrom { get; set; }
        public int ReqTo { get; set; }
        public string Response { get; set; }
        public bool Closed { get; set; }
    
        public virtual CandidateMaster CandidateMaster { get; set; }
        public virtual UserAccountDetail UserAccountDetail { get; set; }
        public virtual UserAccountDetail UserAccountDetail1 { get; set; }
    }
}
