//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionListDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionListDetail()
        {
            this.BatchSessionDetails = new HashSet<BatchSessionDetail>();
        }
    
        public int SessionId { get; set; }
        public int SessionNo { get; set; }
        public int RefTechId { get; set; }
        public bool IsDeleted { get; set; }
        public int MinDuration { get; set; }
        public string PDFMaterialUrl { get; set; }
        public string AssignmentLink { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public bool IsVerified { get; set; }
        public string VerifiedBy { get; set; }
        public System.DateTime VerifiedDate { get; set; }
        public string TopicName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchSessionDetail> BatchSessionDetails { get; set; }
        public virtual TechnologyMaster TechnologyMaster { get; set; }
    }
}
