//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubmissionDetail()
        {
            this.InterviewDetails = new HashSet<InterviewDetail>();
        }
    
        public int SubmissionId { get; set; }
        public System.DateTime Date { get; set; }
        public string VendorName { get; set; }
        public string VendorContactNumber { get; set; }
        public string VendorEmailId { get; set; }
        public string VendorCompanyName { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> PerHourRate { get; set; }
        public string JobTitle { get; set; }
        public string JobLocation { get; set; }
        public string Remarks { get; set; }
        public int RefAssignedId { get; set; }
        public System.DateTime FollowUpDate { get; set; }
        public string StatusOfSubmission { get; set; }
        public string JobPortal { get; set; }
    
        public virtual CandidateAssign CandidateAssign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterviewDetail> InterviewDetails { get; set; }
    }
}
