//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashTechCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskManageMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskManageMaster()
        {
            this.TaskStatusDetails = new HashSet<TaskStatusDetail>();
        }
    
        public int TMId { get; set; }
        public int RefTaskCatId { get; set; }
        public System.DateTime TaskDate { get; set; }
        public System.TimeSpan TaskStartTime { get; set; }
        public System.TimeSpan TaskEndTime { get; set; }
        public string TaskStatus { get; set; }
        public int RefCTId { get; set; }
        public int TotalMin { get; set; }
        public string TaskRemarks { get; set; }
        public string TeamLeadFeedback { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<System.TimeSpan> FeedbackTime { get; set; }
        public string FeedbackBy { get; set; }
    
        public virtual CandidateTechnicalExpertDetail CandidateTechnicalExpertDetail { get; set; }
        public virtual TaskCategoryMaster TaskCategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskStatusDetail> TaskStatusDetails { get; set; }
    }
}
